apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-auth"
spec:
  targets:
  - name: java
  origins:
  - jwt:
      issuer: https://mythaistar.eu.auth0.com/
      jwksUri: https://mythaistar.eu.auth0.com/.well-known/jwks.json
  principalBinding: USE_ORIGIN
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "jwt-auth"
spec:
  host: java.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE